# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1139409c0a80c31fc89f2483d438af8f60a32d3bcd3eda26589ffcf5f603d964ed323fa189eed2165b618c1bd0ae062aa78f1d3658f8bba19bfa9479bfdf73ca

test:
  secret_key_base: 5a8128e98ac08c25085be0a1fad557660029ed1841eddd5c51b172ddc996d0c66f58e75bbcd6464a5e5751dddad254461f91d4feca1ca2f586c1fb919f17d785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
